apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentry

resources:
  - ../base
  - clickhouse.yaml
  - httpproxy.yaml

helmCharts:
  - name: sentry
    version: "29.5.1"
    repo: "https://sentry-kubernetes.github.io/charts"
    releaseName: "sentry"
    namespace: sentry
    valuesFile: values.yaml
